#!/usr/bin/env python 
# -*- coding:utf-8 -*-
from time import sleep

from selenium import webdriver

driver = webdriver.Chrome()
driver.get('https://mail.126.com/')
driver.maximize_window()
driver.switch_to.frame(0)
driver.find_element_by_name('email').send_keys('aaaaa')
sleep(1)
driver.switch_to.default_content()
driver.find_element_by_link_text('网易首页').click()
sleep(2)
driver.switch_to.window(driver.window_handles[-1])
sleep(2)
driver.find_element_by_css_selector('.ntes-nav-mobile-title>em').click()
sleep(2)
driver.close()
sleep(2)
driver.switch_to.window(driver.window_handles[-1])
sleep(3)
driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
sleep(2)
driver.close()
sleep(2)
driver.switch_to.window(driver.window_handles[0])
sleep(2)
driver.find_element_by_link_text('网易智造').click()
sleep(2)
driver.close()
sleep(2)
driver.switch_to.window(driver.window_handles[-1])
sleep(2)
driver.find_element_by_class_name('J-goUser').click()
sleep(2)
driver.switch_to.frame(0)
driver.find_element_by_name('email').send_keys('ccc')
sleep(3)
driver.quit()
